brew "git"
brew "herdr"
brew "mise"

cask "1password"
cask "1password-cli"
cask "chatgpt-classic"
cask "codex"
cask "font-geist-mono"
cask "font-geist-mono-nerd-font"
cask "ghostty"
cask "little-snitch"
cask "tailscale-app"
cask "textmate"
